foss_library/reports/__init__.py
from . import views

foss_library/reports/views.py
from math import ceil

from flask import (
    Blueprint,
    flash,
    render_template,
    request,
    send_file,
)

from foss_library.database import db
from foss_library.books.models import Book
from foss_library.members.models import Member
from foss_library.transactions.models import Transaction
from .helpers import render_jinja_to_pdf


blueprint = Blueprint(
    "reports", __name__, url_prefix="/reports", static_folder="../static"
)


def get_most_popular_books_query():
    most_popular_books_query = (
        Book.query.join(Transaction, Book.id == Transaction.book_id)
        .add_columns(db.text(f"count({Transaction.__tablename__}.id) as popularity"))
        .order_by(db.text("popularity desc"))
        .group_by(Book.id)
    )
    return most_popular_books_query


def get_highest_paying_customers_query():
    highest_paying_customers_query = Member.query.order_by(Member.dues_paid.desc())
    return highest_paying_customers_query


@blueprint.route("/")
def list_reports():
    return render_template("reports/list_reports.html")


@blueprint.route("/most-popular-books/")
def most_popular_books_report():
    on_each_page = 20

    # get page from request args, e.g. /books?page=1
    page = request.args.get("page", 1)
    page = int(page)

    # set limit and offset for SQL query
    limit = on_each_page
    offset = (page - 1) * on_each_page

    most_popular_books_query = get_most_popular_books_query()
    most_popular_books = most_popular_books_query.limit(limit).offset(offset).all()

    total_count = most_popular_books_query.count()
    total_pages = ceil(total_count / on_each_page)

    if page > total_pages:
        flash(f"Page {page} is out of range", "warning")

    return render_template(
        "reports/most_popular_books_report.html",
        most_popular_books=most_popular_books,
        current_page=page,
        total_pages=total_pages,
        offset=offset,
        total_count=total_count,
    )


@blueprint.route("/most-popular-books/download/")
def download_most_popular_books_report():
    query = get_most_popular_books_query()
    books = query.all()

    total_count = len(books)
    offset = 0
    output_path = render_jinja_to_pdf(
        "reports/most_popular_books_report_partial.html",
        "most_popular_books_report_",
        most_popular_books=books,
        offset=offset,
        total_count=total_count,
    )

    return send_file(output_path)


@blueprint.route("/highest-paying-customers/")
def highest_paying_customers_report():
    on_each_page = 20

    # get page from request args, e.g. /books?page=1
    page = request.args.get("page", 1)
    page = int(page)

    # set limit and offset for SQL query
    limit = on_each_page
    offset = (page - 1) * on_each_page

    query = get_highest_paying_customers_query()
    highest_paying_customers = query.limit(limit).offset(offset).all()

    total_count = query.count()
    total_pages = ceil(total_count / on_each_page)

    if page > total_pages:
        flash(f"Page {page} is out of range", "warning")

    return render_template(
        "reports/highest_paying_customers_report.html",
        highest_paying_customers=highest_paying_customers,
        current_page=page,
        total_pages=total_pages,
        offset=offset,
        total_count=total_count,
    )


@blueprint.route("/highest-paying-customers/download/")
def download_highest_paying_customers_report():
    query = get_highest_paying_customers_query()
    customers = query.all()

    total_count = len(customers)
    offset = 0
    output_path = render_jinja_to_pdf(
        "reports/highest_paying_customers_report_partial.html",
        "highest_paying_customers_report_",
        highest_paying_customers=customers,
        offset=offset,
        total_count=total_count,
    )

    return send_file(output_path)

foss_library/templates/reports/highest_paying_customers_report.html
{% extends "layout.html" %}
{% block content %}
<div class="container d-flex my-2">
  <h1 class="fs-2 me-auto">Reports 📈</h1>
  <a class="d-flex justify-content-end text-reset text-decoration-none" href="{{ request.path }}/download/" target="_blank">
    <button class="btn btn-primary">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-download" viewBox="0 0 16 16">
        <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
        <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
      </svg>
      Download as PDF
    </button>
  </a>
</div>

<hr />

{% include "reports/highest_paying_customers_report_partial.html" %}

<nav aria-label="Page navigation" class="d-flex justify-content-center">
  <ul class="pagination pagination-md">
    {% if current_page > 1 %}
      <li class="page-item"><a class="page-link" href="{{ url_for("reports.highest_paying_customers_report", page=current_page-1) }}">Previous</a></li>
    {% else %}
      <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
    {% endif %}

    {% for page_number in range(1, total_pages+1) %}
      {% if page_number == current_page %}
      <li class="page-item active"><a class="page-link selected" href="{{ url_for("reports.highest_paying_customers_report", page=page_number) }}">{{ page_number }}</a></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="{{ url_for("reports.highest_paying_customers_report", page=page_number) }}">{{ page_number }}</a></li>
      {% endif %}
    {% endfor %}

    {% if current_page < total_pages %}
      <li class="page-item"><a class="page-link" href="{{ url_for("reports.highest_paying_customers_report", page=current_page+1) }}">Next</a></li>
    {% else %}
      <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
    {% endif %}
  </ul>
</nav>
{% endblock %}

foss_library/templates/reports/highest_paying_customers_report_partial.html
<div class="container justify-elements-center mx-auto my-2">

  <div class="mb-2">
    <h1 class="fs-3">Highest paying customers</h1>
    {% if total_count is defined %}
    <p class="text-muted">{{ total_count }} results in this report</p>
    {% endif %}
  </div>

  <table class="table">

    <thead>
      <th class="align-middle text-center" scope="col">Rank</th>
      <th class="align-middle text-center" scope="col">Member ID</th>
      <th class="align-middle text-center" scope="col">Name</th>
      <th class="align-middle text-center" scope="col">Email</th>
      <th class="align-middle text-center" scope="col">Dues paid</th>
    </thead>

    <tbody>

      {% for member in highest_paying_customers %}
      <tr>
        <th class="align-middle text-center" scope="row">
          {{ offset + loop.index }}
        </th>
        <td class="align-middle text-center" scope="row">
          {{ member.id }}
        </td>

        <td class="align-middle text-center" scope="row">
          {{ member.name }}
        </td>

        <td class="align-middle text-center" scope="row">
          {{ member.email }}
        </td>

        <td class="align-middle text-center" scope="row">
          ₹{{ member.dues_paid }}
        </td>

      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

foss_library/templates/reports/list_reports.html
{% extends "layout.html" %}
{% block content %}
<div class="container d-flex my-2">
  <h1 class="fs-2 me-auto">Reports 📈</h1>
</div>

<hr />

<div class="container d-flex justify-content-center align-items-middle py-2">
  <table class="table">

    <thead class="thead">
      <th scope="col">#</th>
      <th scope="col">Name</th>
    </thead>

    <tbody>

      <tr>
        <th scope="row">1</th>
        <td><a class="text-reset" href="{{ url_for("reports.most_popular_books_report") }}">Most popular books with their available and total quantity</a></td>
      </tr>

      <tr>
        <th scope="row">2</th>
        <td><a class="text-reset" href="{{ url_for("reports.highest_paying_customers_report") }}">Highest paying customers</a></td>
      </tr>

    </tbody>

  </table>
</div>
{% endblock %}

foss_library/templates/reports/most_popular_books_report.html
{% extends "layout.html" %}
{% block content %}
<div class="container d-flex my-2">
  <h1 class="fs-2 me-auto">Reports 📈</h1>
  <a class="d-flex justify-content-end text-reset text-decoration-none" href="{{ request.path }}/download/" target="_blank">
    <button class="btn btn-primary">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-download" viewBox="0 0 16 16">
        <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
        <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
      </svg>
      Download as PDF
    </button>
  </a>
</div>

<hr />

{% include "reports/most_popular_books_report_partial.html" %}

<nav aria-label="Page navigation" class="d-flex justify-content-center">
  <ul class="pagination pagination-md">
    {% if current_page > 1 %}
      <li class="page-item"><a class="page-link" href="{{ url_for("reports.most_popular_books_report", page=current_page-1) }}">Previous</a></li>
    {% else %}
      <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
    {% endif %}

    {% for page_number in range(1, total_pages+1) %}
      {% if page_number == current_page %}
      <li class="page-item active"><a class="page-link selected" href="{{ url_for("reports.most_popular_books_report", page=page_number) }}">{{ page_number }}</a></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="{{ url_for("reports.most_popular_books_report", page=page_number) }}">{{ page_number }}</a></li>
      {% endif %}
    {% endfor %}

    {% if current_page < total_pages %}
      <li class="page-item"><a class="page-link" href="{{ url_for("reports.most_popular_books_report", page=current_page+1) }}">Next</a></li>
    {% else %}
      <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
    {% endif %}
  </ul>
</nav>
{% endblock %}

foss_library/templates/reports/most_popular_books_report_partial.html
<div class="container justify-elements-center mx-auto my-2">

  <div class="mb-2">
    <h1 class="fs-3">Most popular books</h1>
    {% if total_count is defined %}
    <p class="text-muted">{{ total_count }} results in this report</p>
    {% endif %}
  </div>

  <table class="table">
    <thead>
      <th class="align-middle text-center" scope="col">Rank</th>
      <th class="align-middle text-center" scope="col">Book ID</th>
      <th class="align-middle text-center" scope="col">Title</th>
      <th class="align-middle text-center" scope="col">ISBN</th>
      <th class="align-middle text-center" scope="col">Authors</th>
      <th class="align-middle text-center" scope="col">Available stock</th>
      <th class="align-middle text-center" scope="col">Total stock</th>
      <th class="align-middle text-center" scope="col">Popularity</th>
    </thead>

    <tbody>

      {% for (book, popularity) in most_popular_books %}
      <tr>
        <th class="align-middle text-center" scope="row">
          {{ offset + loop.index }}
        </th>
        <td class="align-middle text-center" scope="row">
          {{ book.id }}
        </td>

        <td class="align-middle text-center" scope="row">
          <a class="text-reset" href="{{ url_for("books.show_book", id=book.id) }}">{{ book.title }}</a>
        </td>

        <td class="align-middle text-center" scope="row">
          {{ book.isbn }}
        </td>

        <td class="align-middle text-center" scope="row">
          {% for author in book.authors.split("/") %}
          <a href="{{ url_for("books.list_books", author=author) }}" class="text-reset">{{ author }}</a>{% if loop.nextitem %}, {% endif %}
          {% endfor %}
        </td>

        <td class="align-middle text-center" scope="row">
          {{ book.available_stock }}
        </td>

        <td class="align-middle text-center" scope="row">
          {{ book.total_stock }}
        </td>

        <td class="align-middle text-center" scope="row">
          {{ popularity }}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>