foss_library/import_data/views.py
from flask import Blueprint, flash, render_template

from foss_library.books.models import Book
from foss_library.utils import flash_form_errors
from .forms import ImportDataForm
from .frappe_api import get_n_books_from_api

blueprint = Blueprint(
    "import_data", __name__, url_prefix="/import", static_folder="../static"
)


@blueprint.route("/", methods=("GET", "POST"))
async def import_data():
    """
    Async view for importing data. Async so that the program can
    run fast and exit before the HTTP request times out
    """
    form = ImportDataForm()

    if form.validate_on_submit():
        count = form.count.data
        title = form.title.data
        authors = form.authors.data
        isbn = form.isbn.data
        publisher = form.publisher.data

        total_results = 0
        added_count = 0
        duplicates_count = 0

        async for book in get_n_books_from_api(
            count, title=title, authors=authors, isbn=isbn, publisher=publisher
        ):
            total_results += 1

            # TODO: add book to DB, on conflict do nothing
            # figure out how to do it with SQLAlchemy
            if Book.query.get(book.id) is None:
                book.save()
                added_count += 1
            else:
                duplicates_count += 1

        if total_results == 0:
            flash("No results found for given search params", "danger")
        else:
            flash(
                f"Got {total_results} results from API. Imported {added_count} books, {duplicates_count} were duplicates",
                "success",
            )

        return render_template("import_data/import_data.html", form=form)

    flash_form_errors(form)
    return render_template("import_data/import_data.html", form=form)

foss_library/members/views.py
from math import ceil

from flask import Blueprint, flash, request, redirect, render_template

from foss_library.decorators import get_model_instance_from_id
from foss_library.utils import flash_form_errors
from .forms import CreateMemberForm, UpdateMemberForm
from .models import Member

blueprint = Blueprint(
    "members", __name__, url_prefix="/members", static_folder="../static"
)


@blueprint.route("/", methods=("GET",))
def list_members():
    """List members"""
    members_on_each_page = 20

    total_pages = max(ceil(Member.query.count() / members_on_each_page), 1)

    # get page from request args, e.g. /books?page=1
    page = request.args.get("page", 1)
    page = int(page)

    if page > 1 and page > total_pages:
        flash(f"Page {page} is out of range", "warning")

    # set limit and offset for SQL query
    limit = members_on_each_page
    offset = (page - 1) * members_on_each_page

    members = (
        Member.query.limit(limit).offset(offset).all()
    )
    return render_template(
        "members/list_members.html",
        members=members,
        current_page=page,
        total_pages=total_pages,
    )


@blueprint.route("/create", methods=("GET", "POST"))
def create_member():
    """Create a new member"""
    form = CreateMemberForm()
    if form.validate_on_submit():
        member = Member()
        form.populate_obj(member)
        member.save()
        flash("Member added successfully!", "success")
        return redirect("/members/")

    flash_form_errors(form)
    if form.errors:
        status_code = 400
    else:
        status_code = 200

    return render_template("members/create_member.html", form=form), status_code


@blueprint.route("/update/<int:id>", methods=("GET", "POST"))
@get_model_instance_from_id(Member)
def update_member(member):
    """Update an existing member"""
    form = UpdateMemberForm(obj=member)
    if form.validate_on_submit():
        form.populate_obj(member)
        member.save()
        flash("Member updated successfully!", "success")
        return redirect("/members/")

    flash_form_errors(form)
    if form.errors:
        status_code = 400
    else:
        status_code = 200

    return render_template("members/update_member.html", form=form), status_code


@blueprint.route("/delete/<int:id>", methods=("POST",))
@get_model_instance_from_id(Member)
def delete_member(member):
    """Delete a member"""
    member.delete()
    flash("Member deleted successfully!", "success")
    return redirect("/members/")

foss_library/reports/views.py
from math import ceil

from flask import (
    Blueprint,
    flash,
    render_template,
    request,
    send_file,
)

from foss_library.database import db
from foss_library.books.models import Book
from foss_library.members.models import Member
from foss_library.transactions.models import Transaction
from .helpers import render_jinja_to_pdf


blueprint = Blueprint(
    "reports", __name__, url_prefix="/reports", static_folder="../static"
)


def get_most_popular_books_query():
    most_popular_books_query = (
        Book.query.join(Transaction, Book.id == Transaction.book_id)
        .add_columns(db.text(f"count({Transaction.__tablename__}.id) as popularity"))
        .order_by(db.text("popularity desc"))
        .group_by(Book.id)
    )
    return most_popular_books_query


def get_highest_paying_customers_query():
    highest_paying_customers_query = Member.query.order_by(Member.dues_paid.desc())
    return highest_paying_customers_query


@blueprint.route("/")
def list_reports():
    return render_template("reports/list_reports.html")


@blueprint.route("/most-popular-books/")
def most_popular_books_report():
    on_each_page = 20

    # get page from request args, e.g. /books?page=1
    page = request.args.get("page", 1)
    page = int(page)

    # set limit and offset for SQL query
    limit = on_each_page
    offset = (page - 1) * on_each_page

    most_popular_books_query = get_most_popular_books_query()
    most_popular_books = most_popular_books_query.limit(limit).offset(offset).all()

    total_count = most_popular_books_query.count()
    total_pages = ceil(total_count / on_each_page)

    if page > total_pages:
        flash(f"Page {page} is out of range", "warning")

    return render_template(
        "reports/most_popular_books_report.html",
        most_popular_books=most_popular_books,
        current_page=page,
        total_pages=total_pages,
        offset=offset,
        total_count=total_count,
    )


@blueprint.route("/most-popular-books/download/")
def download_most_popular_books_report():
    query = get_most_popular_books_query()
    books = query.all()

    total_count = len(books)
    offset = 0
    output_path = render_jinja_to_pdf(
        "reports/most_popular_books_report_partial.html",
        "most_popular_books_report_",
        most_popular_books=books,
        offset=offset,
        total_count=total_count,
    )

    return send_file(output_path)


@blueprint.route("/highest-paying-customers/")
def highest_paying_customers_report():
    on_each_page = 20

    # get page from request args, e.g. /books?page=1
    page = request.args.get("page", 1)
    page = int(page)

    # set limit and offset for SQL query
    limit = on_each_page
    offset = (page - 1) * on_each_page

    query = get_highest_paying_customers_query()
    highest_paying_customers = query.limit(limit).offset(offset).all()

    total_count = query.count()
    total_pages = ceil(total_count / on_each_page)

    if page > total_pages:
        flash(f"Page {page} is out of range", "warning")

    return render_template(
        "reports/highest_paying_customers_report.html",
        highest_paying_customers=highest_paying_customers,
        current_page=page,
        total_pages=total_pages,
        offset=offset,
        total_count=total_count,
    )


@blueprint.route("/highest-paying-customers/download/")
def download_highest_paying_customers_report():
    query = get_highest_paying_customers_query()
    customers = query.all()

    total_count = len(customers)
    offset = 0
    output_path = render_jinja_to_pdf(
        "reports/highest_paying_customers_report_partial.html",
        "highest_paying_customers_report_",
        highest_paying_customers=customers,
        offset=offset,
        total_count=total_count,
    )

    return send_file(output_path)

foss_library/transactions/views.py
from math import ceil

from flask import Blueprint, flash, redirect, render_template, request, url_for
from sqlalchemy import desc

from .models import Transaction

blueprint = Blueprint(
    "transactions", __name__, url_prefix="/transactions", static_folder="../static"
)


@blueprint.route("/", methods=("GET",))
def list_transactions():
    transactions_on_each_page = 20

    page = request.args.get("page", 1)
    page = int(page)

    total_pages = ceil(Transaction.query.count() / transactions_on_each_page)
    if page > 1 and page > total_pages:
        flash(f"Page {page} is out of range", "warning")

    limit = transactions_on_each_page
    offset = (page - 1) * transactions_on_each_page

    transactions = (
        Transaction.query.order_by(desc(Transaction.updated_at))
        .limit(limit)
        .offset(offset)
        .all()
    )

    return render_template(
        "transactions/list_transactions.html",
        transactions=transactions,
        current_page=page,
        total_pages=total_pages,
    )


@blueprint.route("/<int:id>/show", methods=("GET",))
def show_transaction(id):
    transaction = Transaction.query.get_or_404(id)
    return render_template(
        "transactions/show_transaction.html", transaction=transaction
    )


@blueprint.route("/<int:id>/return_book", methods=("POST",))
def return_book(id):
    transaction = Transaction.query.get_or_404(id)
    if transaction.is_completed:
        flash("Book has already been returned", "warning")
        return redirect(url_for("transactions.show_transaction", id=id)), 400

    transaction.return_book_and_pay_dues()
    flash("Book has been returned successfully", "success")
    return redirect(url_for("transactions.show_transaction", id=id))

foss_library/templates/footer.html
<footer>
  <small>
  <ul class="company">
    <li>© Kaustubh Maske Patil</li>
  </ul>

    <ul class="footer-nav">

      <li><a href="https://github.com/nikochiko">About</a></li>

      <li><a href="mailto:ktvm42@gmail.com">Contact</a></li>
    </ul>
  </small>
</footer>

foss_library/templates/layout.html
<!DOCTYPE html>
<!-- taken from: https://github.com/cookiecutter-flask/cookiecutter-flask -->
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
  <!--<![endif]-->
  <head>
    <meta charset="utf-8" />

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="shortcut icon" href="{{static_url_for('static', filename='build/img/favicon.ico') }}">
    <title>
      {% block page_title %} 
        FOSS Library
      {% endblock %}
    </title>
    <meta
      name="description"
      content="{% block meta_description %}{% endblock %}"
    />
    <meta name="author" content="{% block meta_author %}{% endblock %}" />

    <!-- Mobile viewport optimized: h5bp.com/viewport -->
    <meta name="viewport" content="width=device-width" />

    <link
      rel="stylesheet"
      type="text/css"
      href="{{ static_url_for('static', filename='build/main_css.bundle.css') }}"
    />

    {% block css %}{% endblock %}
  </head>
  <body class="{% block body_class %}{% endblock %}">
    {% block body %} {% with form=form %} {% include "nav.html" %} {% endwith %}

    <header>{% block header %}{% endblock %}</header>

    <main role="main">
      {% with messages = get_flashed_messages(with_categories=true) %} {% if
      messages %}
      <div class="row">
        <div class="col-md-12">
          {% for category, message in messages %}
          <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
          </div>
          <!-- end .alert -->
          {% endfor %}
        </div>
        <!-- end col-md -->
      </div>
      <!-- end row -->
      {% endif %} {% endwith %} {% block content %}{% endblock %}
    </main>

    {% include "footer.html" %}

    <!-- JavaScript at the bottom for fast page loading -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="{{ static_url_for('static', filename='build/main_js.bundle.js') }}"></script>
    {% block js %}{% endblock %}
    <!-- end scripts -->
    {% endblock %}
  </body>
</html>

foss_library/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container-fluid">
  <a class="navbar-brand" href="{{ url_for('public.home') }}">
     FOSS Library
  </a>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto">

      {% if request.path == url_for('public.home') %}
      <li class="nav-item active">
      {% else %}
      <li class="nav-item">
      {% endif %}
        <a class="nav-link" href="{{ url_for('public.home') }}">Home
          <span class="sr-only">(current)</span>
        </a>
      </li>

      {% if request.path.startswith('/books') %}
      <li class="nav-item active">
      {% else %}
      <li class="nav-item">
      {% endif %}
        <a class="nav-link" href="{{ url_for('books.list_books') }}">Books
          <span class="sr-only">(current)</span>
        </a>
      </li>
 
      {% if request.path.startswith('/members') %}
      <li class="nav-item active">
      {% else %}
      <li class="nav-item">
      {% endif %}
        <a class="nav-link" href="{{ url_for('members.list_members') }}">Members
          <span class="sr-only">(current)</span>
        </a>
      </li>

      {% if request.path.startswith('/transactions') %}
      <li class="nav-item active">
      {% else %}
      <li class="nav-item">
      {% endif %}
        <a class="nav-link" href="{{ url_for('transactions.list_transactions') }}">Transactions
          <span class="sr-only">(current)</span>
        </a>
      </li>

      {% if request.path.startswith('/import') %}
      <li class="nav-item active">
      {% else %}
      <li class="nav-item">
      {% endif %}
        <a class="nav-link" href="{{ url_for('import_data.import_data') }}">Import data
          <span class="sr-only">(current)</span>
        </a>
      </li>

      {% if request.path.startswith('/reports') %}
      <li class="nav-item active">
      {% else %}
      <li class="nav-item">
      {% endif %}
        <a class="nav-link" href="{{ url_for('reports.list_reports') }}">Reports
          <span class="sr-only">(current)</span>
        </a>
      </li>

    </ul>
    <ul class="navbar-nav my-auto">
      <li class="nav-item active">
        <a class="nav-link">Logged in as Librarian</a>
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
  </div>
</nav>

foss_library/templates/pdf_reports_layout.html
<!DOCTYPE html>
<!-- taken from: https://github.com/cookiecutter-flask/cookiecutter-flask -->
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
  <!--<![endif]-->
  <head>
    <meta charset="utf-8" />

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="shortcut icon" href="{{static_url_for('static', filename='build/img/favicon.ico') }}">
    <title>
      {% block page_title %} 
        FOSS Library
      {% endblock %}
    </title>
    <meta
      name="description"
      content="{% block meta_description %}{% endblock %}"
    />
    <meta name="author" content="{% block meta_author %}{% endblock %}" />

    <!-- Mobile viewport optimized: h5bp.com/viewport -->
    <meta name="viewport" content="width=device-width" />

    <link
      rel="stylesheet"
      type="text/css"
      href="{{ static_url_for('static', filename='build/main_css.bundle.css', _external=True) }}"
    />

    {% block css %}{% endblock %}
  </head>
  <body class="{% block body_class %}{% endblock %}">
    {% block body %}

    <header>{% block header %}{% endblock %}</header>

    <main role="main">
      {% with messages = get_flashed_messages(with_categories=true) %} {% if
      messages %}
      <div class="row">
        <div class="col-md-12">
          {% for category, message in messages %}
          <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
          </div>
          <!-- end .alert -->
          {% endfor %}
        </div>
        <!-- end col-md -->
      </div>
      <!-- end row -->
      {% endif %} {% endwith %} {% block content %}{% endblock %}
    </main>

    {% include "footer.html" %}

    <!-- JavaScript at the bottom for fast page loading -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="{{ static_url_for('static', filename='build/main_js.bundle.js', _external=True) }}"></script>
    {% block js %}{% endblock %}
    <!-- end scripts -->
    {% endblock %}
  </body>
</html>