foss_library/members/models.py
import os

from foss_library.database import CRUDMixin, db
from foss_library.transactions.models import Transaction


MAX_OUTSTANDING_DUES = os.getenv("MAX_OUTSTANDING_DUES", 500)


class Member(db.Model, CRUDMixin):
    __tablename__ = "members"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))
    email = db.Column(db.String(255), unique=True)
    dues_paid = db.Column(db.Integer, default=0, index=True)

    # timestamps
    created_at = db.Column(db.DateTime, default=db.func.now())
    updated_at = db.Column(db.DateTime, default=db.func.now(), onupdate=db.func.now())

    @property
    def outstanding_dues(self):
        """Outstanding dues of this member"""
        txns = Transaction.query.filter_by(
            member_id=self.id,
            returned_at=None,
        ).all()
        return sum(txn.dues for txn in txns)

    @property
    def can_borrow_new_book(self):
        return self.outstanding_dues <= MAX_OUTSTANDING_DUES

foss_library/members/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.fields.html5 import EmailField
from wtforms.validators import Email, InputRequired

from foss_library.utils import UniqueCheck
from .models import Member


class MemberForm(FlaskForm):
    _model = Member

    name = StringField(validators=[InputRequired()])
    email = EmailField(validators=[InputRequired(), Email()])


class CreateMemberForm(MemberForm):
    email = EmailField(validators=[InputRequired(), Email(), UniqueCheck()])


class UpdateMemberForm(MemberForm):
    pass

foss_library/members/__init__.py
from . import models, views

foss_library/members/views.py
from math import ceil

from flask import Blueprint, flash, request, redirect, render_template

from foss_library.decorators import get_model_instance_from_id
from foss_library.utils import flash_form_errors
from .forms import CreateMemberForm, UpdateMemberForm
from .models import Member

blueprint = Blueprint(
    "members", __name__, url_prefix="/members", static_folder="../static"
)


@blueprint.route("/", methods=("GET",))
def list_members():
    """List members"""
    members_on_each_page = 20

    total_pages = max(ceil(Member.query.count() / members_on_each_page), 1)

    # get page from request args, e.g. /books?page=1
    page = request.args.get("page", 1)
    page = int(page)

    if page > 1 and page > total_pages:
        flash(f"Page {page} is out of range", "warning")

    # set limit and offset for SQL query
    limit = members_on_each_page
    offset = (page - 1) * members_on_each_page

    members = (
        Member.query.limit(limit).offset(offset).all()
    )
    return render_template(
        "members/list_members.html",
        members=members,
        current_page=page,
        total_pages=total_pages,
    )


@blueprint.route("/create", methods=("GET", "POST"))
def create_member():
    """Create a new member"""
    form = CreateMemberForm()
    if form.validate_on_submit():
        member = Member()
        form.populate_obj(member)
        member.save()
        flash("Member added successfully!", "success")
        return redirect("/members/")

    flash_form_errors(form)
    if form.errors:
        status_code = 400
    else:
        status_code = 200

    return render_template("members/create_member.html", form=form), status_code


@blueprint.route("/update/<int:id>", methods=("GET", "POST"))
@get_model_instance_from_id(Member)
def update_member(member):
    """Update an existing member"""
    form = UpdateMemberForm(obj=member)
    if form.validate_on_submit():
        form.populate_obj(member)
        member.save()
        flash("Member updated successfully!", "success")
        return redirect("/members/")

    flash_form_errors(form)
    if form.errors:
        status_code = 400
    else:
        status_code = 200

    return render_template("members/update_member.html", form=form), status_code


@blueprint.route("/delete/<int:id>", methods=("POST",))
@get_model_instance_from_id(Member)
def delete_member(member):
    """Delete a member"""
    member.delete()
    flash("Member deleted successfully!", "success")
    return redirect("/members/")

foss_library/templates/members/create_member.html
{% extends "layout.html" %}
{% block content %}
<div class="container justify-elements-center mx-auto my-2 ">
  <h1 class="fs-2 me-auto">Add a new member 🧑</h1>
  <form class="row g-3" method="POST">
    {{ form.csrf_token }}
    <div class="form-group col-md-6 py-1">
      <b>{{ form.name.label(class="form-label") }}</b>
      {{ form.name(class="form-control", placeholder="John Doe") }}
      <small>Both first name and last name</small>
    </div>
    <div class="form-group col-md-6 py-1">
      <b>{{ form.email.label(class="form-label") }}</b>
      {{ form.email(class="form-control", placeholder="johndoe@example.com") }}
    </div>
    <div class="col-md-3">
      <button class="btn btn-primary" type="submit">Submit</button>
    </div>
  </form>
</div>

{% endblock %}

{% block js %}
    <script>
      $('.alert').alert();
    </script>
{% endblock %}

foss_library/templates/members/list_members.html
{% extends "layout.html" %}
{% block content %}
<div class="container d-flex my-2">
  <h1 class="fs-2 me-auto">Members</h1>
  <a class="fs-2 mx-1" href="{{ url_for("members.create_member") }}">
    <button class="btn btn-primary">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-lg" viewBox="0 0 16 16">
        <path d="M8 0a1 1 0 0 1 1 1v6h6a1 1 0 1 1 0 2H9v6a1 1 0 1 1-2 0V9H1a1 1 0 0 1 0-2h6V1a1 1 0 0 1 1-1z"/>
      </svg>
    </button>
  </a>
</div>

<hr />

<div class="container">
  {% if not members %}
    <div class="jumbotron py-3">
      <div class="row">
        <div class="col-6 d-flex justify-content-center align-items-center">
          <div class="row d-flex justify-content-center align-items-center">
            <h1 class="fs-3">No one's here yet</h1>
            <p>
              <small>Start adding members using the + icon on the top right!</small>
              <br />
              <small>And enjoy the easter egg below :D</small>
            </p>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row mb-2">
        <div class="col-4"></div>
        <div class="col-4">
          <div>
            <h1>The Road Not Taken</h1>
            <small><i>- Robert Frost</i></small>
          </div>
        </div>
        <div class="col-4"></div>
      </div>

      <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
          <p>
            Two roads diverged in a yellow wood,<br />
            And sorry I could not travel both<br />
            And be one traveler, long I stood<br />
            And looked down one as far as I could<br />
            To where it bent in the undergrowth;<br />
          </p>

          <p>
            Then took the other, as just as fair,<br />
            And having perhaps the better claim,<br />
            Because it was grassy and wanted wear;<br />
            Though as for that the passing there<br />
            Had worn them really about the same,<br />
          </p>

          <p>
            And both that morning equally lay<br />
            In leaves no step had trodden black.<br />
            Oh, I kept the first for another day!<br />
            Yet knowing how way leads on to way,<br />
            I doubted if I should ever come back.<br />
          </p>

          <p>
            I shall be telling this with a sigh<br />
            Somewhere ages and ages hence:<br />
            Two roads diverged in a wood, and I<br />
            I took the one less traveled by,<br />
            And that has made all the difference.<br />
          </p>
        </div>
        <div class="col-4"></div>
      </div>
    </div>

  {% else %}

    <table class="table">
      <thead>
        <th class="text-center" scope="col">#</th>
        <th class="text-center" scope="col">Name</th>
        <th class="text-center" scope="col">Email</th>
        <th class="text-center" scope="col">Dues paid</th>
        <th class="text-center" scope="col">Unreturned books</th>
        <th class="text-center" scope="col">Outstanding dues</th>
        <th class="text-center" scope="col">Update</th>
        <th class="text-center" scope="col">Unregister</th>
      </thead>
      <tbody>

      {% for member in members %}

        <tr>
          <th class="align-middle text-center" scope="row">{{ member.id }}</th>

          <td class="align-middle text-center">{{ member.name }}</td>

          <td class="align-middle text-center"><a class="text-reset" href="mailto:{{ member.email }}">{{ member.email }}</a></td>

          <td class="align-middle text-center">{{ member.dues_paid }}</div></td>

          <td class="align-middle text-center">{{ member.unreturned_books|length }}</td>

          <td class="align-middle text-center">{{ member.outstanding_dues }}</td>

          <td class="align-middle text-center">
            <a class="d-flex justify-content-center align-items-center text-decoration-none" href="{{ url_for("members.update_member", id=member.id) }}">
              <button class="btn btn-link text-reset text-decoration-none d-inline-flex justify-content-center align-items-center px-0">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                  <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                  <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                </svg>
              </button>
            </a>
          </td>

          <td class="align-middle">
            <form class="d-flex justify-content-center align-items-center text-danger" action="{{ url_for("members.delete_member", id=member.id) }}" method="POST">
              <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
              <button
                type="submit"
                class="btn btn-link text-reset text-decoration-none d-inline-flex justify-content-center align-items-center px-0"
                onclick="return confirm('Are you sure you want to unregister this member?');"
              >
                  <svg class="icon" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                  </svg>
              </button>
            </form>
          </td>
        </tr>

        {% endfor %}

      </tbody>
    </table>
  {% endif %}

  {% if members|length > 0 %}
    <nav aria-label="Page navigation" class="d-flex justify-content-center">
      <ul class="pagination pagination-md">
        {% if current_page > 1 %}
          <li class="page-item"><a class="page-link" href="{{ url_for("books.list_books", page=current_page-1) }}">Previous</a></li>
        {% else %}
          <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
        {% endif %}

        {% for page_number in range(1, total_pages+1) %}
          {% if page_number == current_page %}
          <li class="page-item active"><a class="page-link selected" href="{{ url_for("books.list_books", page=page_number) }}">{{ page_number }}</a></li>
          {% else %}
            <li class="page-item"><a class="page-link" href="{{ url_for("books.list_books", page=page_number) }}">{{ page_number }}</a></li>
          {% endif %}
        {% endfor %}

        {% if current_page < total_pages %}
          <li class="page-item"><a class="page-link" href="{{ url_for("books.list_books", page=current_page+1) }}">Next</a></li>
        {% else %}
          <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
        {% endif %}
      </ul>
    </nav>
  {% endif %}
{% endblock %}

foss_library/templates/members/update_member.html
{% extends "layout.html" %}
{% block content %}
<div class="container justify-elements-center mx-auto my-2 ">
  <h1 class="fs-2 me-auto">Update member 🧑</h1>
  <form class="row g-3" method="POST">
    {{ form.csrf_token }}
    <div class="form-group col-md-6 py-1">
      <b>{{ form.name.label(class="form-label") }}</b>
      {{ form.name(class="form-control", placeholder="John Doe") }}
      <small>Both first name and last name</small>
    </div>
    <div class="form-group col-md-6 py-1">
      <b>{{ form.email.label(class="form-label") }}</b>
      {{ form.email(class="form-control", placeholder="johndoe@example.com") }}
    </div>
    <div class="col-md-3">
      <button class="btn btn-primary" type="submit">Submit</button>
    </div>
  </form>
</div>

{% endblock %}

{% block js %}
    <script>
      $('.alert').alert();
    </script>
{% endblock %}